### ISSUE TITLE
The CSS is not visible on the web inspector

### ISSUE THREAD

**Issue by MKlblangenois** [unbug/MIHTool#4]
Hi everyone !

Since one week, the css of my element is not visible on the web inspector. So, in fact, I can't debug my page :/

**Comment by unbug** [comment]
The issue might cause by your page enable [content security policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP)

**Comment by kh00** [comment]
> Hi everyone !
> 
> Since one week, the css of my element is not visible on the web inspector. So, in fact, I can't debug my page :/
