### ISSUE TITLE
"No 'Access-Control-Allow-Origin' header" on either local http server or https://i.mihtool.com/dev/client/

### ISSUE THREAD

**Issue by cepm-nate** [unbug/MIHTool#5]
Trying to open the "Web Inspector" for a generic website on an iPad gives "Targets: None" and "Clients: Waiting for connection".

Steps to reproduce:
- Download and install MIH Tool from Apple store.
- Open 'MIH Tool' app.
- Visit http://www.google.com
- Open right side hamburger menu
- Ensure "HTTP Server" is ON
- Tap "Web Inspector"
- Web Inspector slides up from bottom of screen
- Display on Web Inspector says "Targets - None" and "Clients - Waiting for connection..." --- none of the other tabs in the inspector show useful information.

Alternate ways to reproduce the same issue:
- Visit the http address under "HTTP Server", on a desktop
- Visit the link "Web Inspector Remote (Recommend)"
- Result: Same "Targets - None" issue.

I've also tried using the "Online Web Inspector", same thing.

 I can INSPECT (in chrome) the winre page. It's console shows:
````
WebSocketXhr.amd.js:230 POST http://weinre.mihtool.com/ws/client 502 (Bad Gateway)
:1630/devtool/client/#******* Access to XMLHttpRequest at 'http://weinre.mihtool.com/ws/client' from origin 'http://192.168.254.37:1630' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
````

Is there any way to set the internal http server to reply with the 'Access-Control-Allow-Origin' header?

**Comment by unbug** [comment]
Thanks @cepm-nate , you made a nice report. The server is down, Im working on it. BRB

**Comment by unbug** [comment]
![IMG_3109](https://user-images.githubusercontent.com/799578/66967970-640f9380-f0b5-11e9-94de-5a3c760652a3.PNG)

Service is back! All Good!
BTW, the screenshot is one of the best features of MIHTool - "Action Extension for Safari". Give it a try.

**Comment by Laureneb27** [comment]
I've got the same error :/

**Comment by unbug** [comment]
@Laureneb27 The service was down, please try again :)

**Comment by Laureneb27** [comment]
@unbug Thank you so much, it's working again !

**Comment by AlexArdelean** [comment]
Is the service down? I'm getting this same issue.

**Comment by unbug** [comment]
@AlexArdelean I'll look into it, hang on....

**Comment by swinokur** [comment]
I am also seeing the same issue, is the service down again?

**Comment by ionurboz** [comment]
same here
